SpotifyWrapped/urls.py
from django.contrib import admin
from django.urls import path, include
from wrapped.views import WrappedRedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wrapped/', include("wrapped.urls")),
    path('', WrappedRedirectView.as_view()),
]

Spotify_Wrapped_Site/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

api/urls.py
from django.urls import path
from .views import (AuthURL, spotify_callback, IsAuthenticated, LinkSpotifyToken, UserStats, UserWrapped, SingleWrapped,
                    ProfilePicture, Visibility, Game)


urlpatterns = [
    path('authenticate', AuthURL.as_view()),
    path('redirect', spotify_callback),
    path('authenticated', IsAuthenticated.as_view()),
    path('link', LinkSpotifyToken.as_view()),
    path('taste', UserStats.as_view()),
    path('wrap', UserWrapped.as_view()),
    path('wrap/<int:id>', SingleWrapped.as_view(), name='wrap'),
    path('wrap/<int:id>/visibility', Visibility.as_view()),
    path('wrap/<int:id>/game', Game.as_view()),
    path('picture', ProfilePicture.as_view()),
]

wrapped/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import IndexView, SignUpView, LogInView, LinkTokenView, ResetPasswordView, ResetPasswordConfirmView, \
    DeveloperContactView, FeedbackView, AccountView, WrappedView, SavedView, DeleteWrappedView

app_name = 'wrapped'

urlpatterns = [
    path("link-token/", LinkTokenView.as_view(), name="link_token"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("login/", LogInView.as_view(), name="login"),
    path("reset/", ResetPasswordView.as_view(), name="reset_password"),
    path("reset/<uidb64>/<token>/", ResetPasswordConfirmView.as_view(), name="password_reset_confirm"),
    path("", IndexView.as_view(), name="home"),
    path("help/", DeveloperContactView.as_view(), name="developer"),
    path("feedback/", FeedbackView.as_view(), name="feedback"),
    path("account/", AccountView.as_view(), name="account"),
    path("wrap/<int:pk>", WrappedView.as_view(), name="wrap"),
    path("wrap/<int:pk>/delete", DeleteWrappedView.as_view(), name="delete"),
    path('', include('django.contrib.auth.urls')),
    path("saved/", SavedView.as_view(), name="saved"),

]

wrapped/models.py
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from api.models import SpotifyToken, SpotifyArtist, SpotifyTrack, SpotifyAlbum
from django.core.validators import MaxValueValidator
from django.db import models
import random


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    token = models.OneToOneField(SpotifyToken, null=True, blank=True, on_delete=models.CASCADE)


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


class Feedback(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField(max_length=50)
    subject = models.CharField(max_length=100)
    message = models.CharField(max_length=10000)


post_save.connect(create_user_profile, sender=User)


class SpotifyUserWrap(models.Model):
    THEME = (
        ("no", "None"),
        ("ch", "Christmas"),
        ("hw", "Halloween"),
        ("ea", "Easter"),
    )
    TERMS = (
        ('short', '4 Weeks'),
        ('medium', '6 Months'),
        ('long', '1 Year'),
    )

    created_at = models.DateTimeField(auto_now_add=True)
    theme = models.CharField(default="no", max_length=2, choices=THEME)
    # When the user who generated these wraps deletes their account, the on_delete will delete their wraps
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='wraps')
    term = models.CharField(max_length=6, choices=TERMS)
    public = models.BooleanField(default=False)

    tracks_by_top_artist = models.PositiveIntegerField(default=0)
    top_track_by_top_artist = models.ForeignKey(SpotifyTrack, on_delete=models.CASCADE,
                                                related_name='top_track_by_top_artist_wraps', blank=True, null=True)

    tracks_in_top_album = models.PositiveIntegerField(default=0)
    top_track_in_top_album = models.ForeignKey(SpotifyTrack, on_delete=models.CASCADE,
                                               related_name='top_track_in_top_album_wraps', blank=True, null=True)

    top_track_by_top_artist_of_top_genre = models.ForeignKey(SpotifyTrack, on_delete=models.CASCADE,
                                                             related_name='top_track_by_top_artist_of_top_genre_wraps',
                                                             blank=True, null=True)

    most_popular_track = models.ForeignKey(SpotifyTrack, on_delete=models.CASCADE,
                                           related_name='most_popular_track_wraps',
                                           blank=True, null=True)
    track_popularity = models.CharField(max_length=10, default='0000000000')
    average_popularity = models.FloatField(default=0)
    game_complete = models.BooleanField(default=False)
    score = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(5)])


class TopTrackItem(models.Model):
    wrapped = models.ForeignKey(SpotifyUserWrap, on_delete=models.CASCADE, related_name='top_tracks')
    track = models.ForeignKey(SpotifyTrack, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']


class TopArtistItem(models.Model):
    wrapped = models.ForeignKey(SpotifyUserWrap, on_delete=models.CASCADE, related_name='top_artists')
    artist = models.ForeignKey(SpotifyArtist, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']


class TopAlbumItem(models.Model):
    wrapped = models.ForeignKey(SpotifyUserWrap, on_delete=models.CASCADE, related_name='top_albums')
    album = models.ForeignKey(SpotifyAlbum, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']


class TopGenreItem(models.Model):
    wrapped = models.ForeignKey(SpotifyUserWrap, on_delete=models.CASCADE, related_name='top_genres')
    name = models.CharField(max_length=100)
    freq = models.FloatField()
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']


class TopArtistOfGenre(models.Model):
    genre = models.ForeignKey(TopGenreItem, on_delete=models.CASCADE, related_name='top_artists')
    artist = models.ForeignKey(SpotifyArtist, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']


class TopTrackOfAlbum(models.Model):
    album = models.ForeignKey(TopAlbumItem, on_delete=models.CASCADE, related_name='top_tracks')
    track = models.ForeignKey(SpotifyTrack, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']


class HighLowGameQuestion(models.Model):
    wrapped = models.ForeignKey(SpotifyUserWrap, on_delete=models.CASCADE, related_name='highlow_game_questions')
    track = models.ForeignKey(SpotifyTrack, on_delete=models.CASCADE)
    rank = models.PositiveIntegerField()
    order = models.PositiveIntegerField()
    answer = models.IntegerField()

    class Meta:
        ordering = ['order']


class GuessingGameQuestion(models.Model):
    wrapped = models.ForeignKey(SpotifyUserWrap, on_delete=models.CASCADE, related_name='guess_game_questions')
    track = models.ForeignKey(SpotifyTrack, on_delete=models.CASCADE)
    rank = models.PositiveIntegerField()
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']


class WrappedSlide(models.Model):
    THEMES = (
        ('wrapped1', 'Default 1'),
        ('wrapped2', 'Default 2'),
        ('wrapped3', 'Default 3'),
        ('wrapped4', 'Default 4'),
        ('wrapped5', 'Default 5'),
        ('wrapped6', 'Default 6'),
        ('wrapped7', 'Default 7'),
    )
    LAYOUTS = (
        ('v1', 'Default 1'),
    )

    wrapped = models.ForeignKey(SpotifyUserWrap, on_delete=models.CASCADE, related_name='slides')
    number = models.PositiveIntegerField()
    colors = models.CharField(max_length=10, choices=THEMES, default=None, blank=True, null=True)
    layout = models.CharField(max_length=2, choices=LAYOUTS)

    def save(self, *args, **kwargs):
        if not self.colors:
            self.colors = random.choices(self.THEMES)[0][0]
        if not self.layout:
            self.layout = random.choices(self.LAYOUTS)[0][0]
        super(WrappedSlide, self).save(*args, **kwargs)

    class Meta:
        ordering = ['number']

wrapped/forms.py
from django import forms
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from wrapped.models import Feedback

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.forms import UserChangeForm

class FeedbackForm(forms.ModelForm):
    first_name = forms.CharField(label="First Name", max_length=20)
    last_name = forms.CharField(label="Last Name", max_length=20)
    email = forms.EmailField(label="Email")
    subject = forms.CharField(label="Subject", max_length=100)
    message = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Feedback
        fields = ('first_name', 'last_name', 'email', 'subject', 'message')


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='Enter a valid email address.')

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class AccountForm(forms.Form):
    username = forms.CharField(max_length=250, required=False)
    email = forms.EmailField(required=False)
    current_password = forms.CharField(widget=forms.PasswordInput, required=False)
    new_password = forms.CharField(widget=forms.PasswordInput, required=False)
    confirm_password = forms.CharField(widget=forms.PasswordInput, required=False)
    
    def clean(self):
        cleaned_data = super().clean()

        current_password = cleaned_data.get('current_password')
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')

        if new_password or confirm_password:
            if not current_password:
                raise ValidationError("Current password is required to change the password.")
            if new_password != confirm_password:
                raise ValidationError("New password and confirm password must match.")

        return cleaned_data

templates/wrapped/pages/account.html
{% extends "wrapped/index.html" %}
{% block title %}Account Settings{% endblock %}
{% block css %}{% endblock %}

{% block content %}
    <div class="col-span-full md:col-start-4 md:col-span-6 lg:col-start-4 lg:col-span-6 pt-4">
    <form class="card bg-base-200 shadow-xl mb-4" method="POST">
        {% csrf_token %}
        <div class="card-body p-6 md:p-8">
            <h1 class="text-3xl font-semibold text-center">Account Settings</h1>

            <div class="form-group mb-4">
                <label for="id_username">Username:</label>
                <div class="helptext" id="id_username_helptext">150 characters or fewer. Letters, digits, and @/./+/-/_ only.</div>
                {{ form.username }}
                {% if form.username.errors %}
                    <div class="error text-red-600 font-bold">{{ form.username.errors.0 }}</div>
                {% endif %}
            </div>

            <div>
                <label for="id_email">Email:</label>
                <div class="helptext" id="id_email_helptext">Enter a valid email address.</div>
                {{ form.email }}
                {% if form.email.errors %}
                    <div class="error text-red-600 font-bold">{{ form.email.errors.0 }}</div>
                {% endif %}
            </div>

            <h2 class="text-2xl font-medium mt-4">Change Password</h2>
            <div>
                <label for="id_current_password">Current Password:</label>
                <div class="helptext" id="id_current_password_helptext">Enter current password</div>
                {{ form.current_password }}
                {% if form.current_password.errors %}
                    <div class="error text-red-600 font-bold">{{ form.current_password.errors.0 }}</div>
                {% endif %}
            </div>
            <div class="form-control mb-4">
                <label for="id_new_password">New Password:</label>
                {{ form.new_password }}
                <div class="helptext" id="id_new_password_helptext">Enter new password</div>
                <div class="helptext" id="id_password1_helptext">
                    <ul>
                        <li>Your password cannot be similar to your personal information</li>
                        <li>Your password must contain at least 8 characters.</li>
                        <li>Your password cannot be commonly used or guessable.</li>
                        <li>Your password cannot be entirely numeric.</li>
                    </ul>
                </div>
                {% if form.new_password.errors %}
                    <div class="error text-red-600 font-bold">{{ form.new_password.errors.0 }}</div>
                {% endif %}
            </div>
            <div class="mb-4">
                <label for="id_confirm_password">Password confirmation:</label>
                <div class="helptext" id="id_password2_helptext">Re-enter new password</div>
                {{ form.confirm_password }}
                {% if form.confirm_password.errors %}
                    <div class="error text-red-600 font-bold">{{ form.confirm_password.errors.0 }}</div>
                {% endif %}
            </div>

            {% if form.non_field_errors %}
                <div class="error text-red-600 font-bold mb-4">
                    {% for error in form.non_field_errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}

            <div class="card-actions justify-center">
                <button type="submit" class="btn btn-accent">Save Changes</button>
            </div>

            <div class="card-actions justify-center mt-4">
                <button type="button" class="btn btn-error" onclick="confirmDeletion()">Delete Account</button>
            </div>
        </div>
        </form>
    </div>
    <script>
        function confirmDeletion() {
            if (confirm("Are you sure you want to delete your account? This action cannot be undone.")) {
                const form = document.createElement('form');
                form.method = 'POST';
                form.action = ""; 

                const csrfInput = document.createElement('input');
                csrfInput.type = 'hidden';
                csrfInput.name = 'csrfmiddlewaretoken';
                csrfInput.value = '{{ csrf_token }}';
                form.appendChild(csrfInput);

                const deleteInput = document.createElement('input');
                deleteInput.type = 'hidden';
                deleteInput.name = 'delete_account';
                deleteInput.value = '1'; // Arbitrary value to identify the request
                form.appendChild(deleteInput);

                document.body.appendChild(form);
                form.submit();
            }
        }
    </script>

{% endblock %}
{% block scripts %}{% endblock %}

templates/wrapped/pages/feedback.html
{% extends 'wrapped/index.html' %}
{% load static %}
{% block title %}Contact Us{% endblock %}
{% block css %}{% endblock %}
{% block content %}
    <form class="card bg-base-200 shadow-xl col-span-4 md:col-span-6 col-start-1 md:col-start-2 lg:col-start-4 mb-16" method="POST">
        <div class="card-body">
            <h1 class="text-center">Contact Us</h1>
                {% csrf_token %}
                {{ form }}
            <div class="card-actions justify-center">
                <button type="submit" class="btn btn-accent">Send</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/wrapped/pages/help.html
{% extends "wrapped/index.html" %}
{% load static %}
{% block title %}Help{% endblock %}
{% block css %}
    <style>
        .help {
            font-weight: 600;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="col-span-full space-y-16">
    <!-- About Section -->
        <section id="about-section" class="col-span-full">
            <h1 class="text-4xl font-bold text-center mb-4 pt-4">About</h1>
            <p class="text-lg mb-8 max-w-3xl mx-auto text-center">
                We're a team of passionate developers and designers. Our mission is to bring data and design together in
                a fun, engaging way, letting users relive their music journey with a personalized Spotify Wrapped
                experience. No matter the time of year, anyone can get real-time data on their listening habits.
            </p>
        </section>
        
        <!-- Meet the Team Section -->
        <section id="meet-the-team-section" class="col-span-full">
            <h2 class="text-4xl font-bold text-center mb-8">Meet the Team</h2>

             <!-- Member 1 -->
        <div class="flex flex-col md:flex-row items-center gap-8 mb-8 px-4 md:px-0">
            <div class="flex-shrink-0">
                <img src="{% static '/wrapped/img/camtien.jpg' %}" alt="Team Member 1" class="w-48 h-48 rounded-full
                object-cover">
            </div>
            <div class="text-center md:text-left space-y-2 flex-grow">
                <h3 class="text-2xl font-semibold">Camtien Nguyen</h3>
                <h4 class="text-lg font-medium">Front-End Developer</h4>
                <p>Hi I'm Camtien! As the front-end developer, I am responsible for designing and implementing the user
                    interface, ensuring smooth, visually appealing, and intuitive user experience. My role involves
                    working closely with design specifications to create responsive layouts and style components using
                    Figma, Tailwind CSS, and GSAP. I work closely with the back-end team to integrate design and data
                    seamlessly for you!
                </p>
            </div>
        </div>

            <!-- Member 2 (Matthew) -->
        <div class="flex flex-col md:flex-row-reverse items-center gap-8 mb-12">
            <div class="flex-shrink-0 mb-4 md:mb-0">
                <img src="{% static '/wrapped/img/dev_matthew.png' %}" alt="Team Member 2, Matthew" class="w-48 h-48 rounded-full object-cover">
            </div>
            <div class="text-center md:text-left space-y-2 flex-grow">
                <h3 class="text-2xl font-semibold">Matthew Nehme-Haily</h3>
                <h4 class="text-lg font-medium">Full-Stack Developer</h4>
                <p> I'm Matthew o/. I am a Full-Stack Dev for this Spotify Wrapped project. I worked mainly in 
                    creating the user authentication flow, adding usability for the Spotify API, and features such as
                    the developer contact and social sharing. 
                </p>
            </div>
        </div>

            <!-- Member 3 (Aidan) -->
        <div class="flex flex-col md:flex-row items-center gap-8 mb-12">
            <div class="flex-shrink-0">
                <img src="{% static '/wrapped/img/dev_aidan.jpg' %}" alt="Team Member 3, Aidan" class="w-48 h-48 rounded-full object-cover">
            </div>
            <div class="text-center md:text-left space-y-2 flex-grow">
                <h3 class="text-2xl font-semibold">Aidan Mascoli</h3>
                <h4 class="text-lg font-medium">Full-Stack Developer</h4>
                <p>Hello! I'm Aidan :). I worked on a bunch of things, but the biggest one was probably wrapped
                generation on the backend, as well as the wrapped frontend development, specifically animations. Other
                than that I worked closely with both the frontend and backend teams to help with their tasks, and assist
                them over any roadblocks they ran into.</p>
            </div>
        </div>

            <!-- Member 4 (Temi) -->
        <div class="flex flex-col md:flex-row-reverse items-center gap-8 mb-12">
            <div class="flex-shrink-0 mb-4 md:mb-0">
                <img src="{% static '/wrapped/img/TemiPic.jpg' %}" alt="Team Member 4, Temi" class="w-48 h-48 rounded-full object-cover">
            </div>
            <div class="text-center md:text-left space-y-2 flex-grow">
            <h3 class="text-2xl font-semibold">Temi Cole</h3>
            <h4 class="text-lg font-medium">Backend Developer</h4>
            <p>Hello I'm Temi! I am a backend developer. I contributed to development of the account settings. I also assisted with organizing the users' statistical information.</p>
            </div>
        </div>

            <!-- Member 5 (Elijah) -->
        <div class="flex flex-col md:flex-row items-center gap-8 mb-12">
            <div class="flex-shrink-0">
                <img src="{% static '/wrapped/img/dev_elijah.jpg' %}" alt="Team Member 5, Elijah" class="w-48 h-48 rounded-full object-cover">
            </div>
            <div class="text-center md:text-left space-y-2 flex-grow">
                <h3 class="text-2xl font-semibold">Elijah Rabinovich</h3>
                <h4 class="text-lg font-medium">Backend Developer</h4>
                <p>I'm Elijah. I am our scrum master as well as back-end engineer for this Spotify Wrapped project. I
                worked primarily on assisting others with their tasks, setting up web-hosting, as well as logic and
                design for some of the back-end data parsing related to user's top 50 songs as well as finding and
                solving bugs.</p>
            </div>
        </div>

        </section>

        <!-- Contact Button Section -->
        <div class="col-span-12 text-center mt-16 mb-12 pt-4">
            <a href="{% url 'wrapped:feedback' %}" class="btn btn-accent mb-8">
                Contact the Developers
            </a>
        </div>
    </div>

{% endblock content %}

templates/wrapped/pages/linking.html
{% extends 'wrapped/index.html' %}
{% load static %}

{% block title %}Connecting{% endblock %}
{% block css %}{% endblock %}
    
{% block content %}
    <div class="col-span-4 col-start-1 md:col-start-3 lg:col-start-5 text-center flex flex-col items-center gap-3">
        {% if not user.is_authenticated %}
            <h3>Unable to Link Your Spotify Account</h3>
            <p>Your Spotify account could not be linked because you are not logged into Spotify Wrapper.</p>
            <a id="goHome" href="{% url 'wrapped:home' %}" class="btn btn-accent">Go Back Home</a>
        {% else %}
            <h3>Linking Your Spotify Account</h3>
            <p>You should be redirected automatically on success.</p>
            <a id="goHome" href="{% url 'wrapped:home' %}" class="btn btn-accent">Go Back Home</a>
        {% endif %}
    </div>
{% endblock %}

{% block scripts %}
    <script>document.addEventListener('DOMContentLoaded', getLinkToken)</script>
{% endblock %}

templates/wrapped/pages/profile.html
{% extends "wrapped/index.html" %}
{% block title %}Profile{% endblock %}
{% block css %}{% endblock %}

{% block content %}
    <div class="profile-container flex items-center mt-16 mb-8">
    <!-- Profile Picture -->
    <div class="profile-pic relative w-32 h-32 rounded-full overflow-hidden cursor-pointer hover:bg-gray-700">
        <img src="{% static 'path/to/default-profile.jpg' %}" alt="Profile Picture" class="w-full h-full object-cover">
        <!-- Hidden input for profile picture upload -->
        <input type="file" accept="image/*" class="absolute inset-0 opacity-0 cursor-pointer" id="profile-upload">
    </div>

    <!-- Display Name Field -->
    <div class="ml-6">
        <label for="display_name" class="block text-lg font-medium">Display Name</label>
        <input type="text" name="display_name" id="display_name" class="input input-bordered w-full max-w-xs" value="{{ display_name }}">
    </div>
</div>

{% endblock %}
{% block scripts %}{% endblock %}

templates/wrapped/pages/saved.html
{% extends "wrapped/index.html" %}
{% load static %}
{% block title %}Saved{% endblock %}
{% block css %}
    <link rel="stylesheet" href="https://use.typekit.net/lha8mkp.css">
    <style>
        .saved {
            font-weight: 600;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="col-span-full space-y-16">
        <table class="table">
            <thead>
            <tr>
                <th>Cover</th>
                <th>Time Duration</th>
                <th>Date Created</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for wrap in wraps %}
                <tr class="hover">
                    <td>
                        <div class="size-36 relative">
                            <div class="absolute -inset-[258px] scale-[.218] overflow-hidden"
                                 data-theme="{{ wrap.slides.0.colors }}">
                                {% with "wrapped/wraps/s0"|add:wrap.slides.0.layout|add:".html" as template %}
                                    {% include template with term=wrap.term id=forloop.counter %}
                                {% endwith %}
                            </div>
                        </div>
                    </td>
                    <td> {% if wrap.term == 'short' %}
                        4 Week
                    {% elif wrap.term == 'medium' %}
                        6 Month
                    {% else %}
                        1 Year
                    {% endif %} </td>
                    <td>{{ wrap.created_at|date:"F d, Y" }}</td>
                    <td>
                        <a href="{{ wrap.url }}" class="btn btn-ghost size-10 p-2 min-h-0">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
                                <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                            </svg>
                        </a>
                        <form method="POST" action="{% url 'wrapped:delete' wrap.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-error btn-ghost size-10 p-2 min-h-0">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                          d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"/>
                                </svg>
                            </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}