SpotifyWrapped/urls.py
from django.contrib import admin
from django.urls import path, include
from wrapped.views import WrappedRedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wrapped/', include("wrapped.urls")),
    path('', WrappedRedirectView.as_view()),
]

Spotify_Wrapped_Site/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

api/urls.py
from django.urls import path
from .views import (AuthURL, spotify_callback, IsAuthenticated, LinkSpotifyToken, UserStats, UserWrapped, SingleWrapped,
                    ProfilePicture, Visibility, Game)


urlpatterns = [
    path('authenticate', AuthURL.as_view()),
    path('redirect', spotify_callback),
    path('authenticated', IsAuthenticated.as_view()),
    path('link', LinkSpotifyToken.as_view()),
    path('taste', UserStats.as_view()),
    path('wrap', UserWrapped.as_view()),
    path('wrap/<int:id>', SingleWrapped.as_view(), name='wrap'),
    path('wrap/<int:id>/visibility', Visibility.as_view()),
    path('wrap/<int:id>/game', Game.as_view()),
    path('picture', ProfilePicture.as_view()),
]

wrapped/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import IndexView, SignUpView, LogInView, LinkTokenView, ResetPasswordView, ResetPasswordConfirmView, \
    DeveloperContactView, FeedbackView, AccountView, WrappedView, SavedView, DeleteWrappedView

app_name = 'wrapped'

urlpatterns = [
    path("link-token/", LinkTokenView.as_view(), name="link_token"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("login/", LogInView.as_view(), name="login"),
    path("reset/", ResetPasswordView.as_view(), name="reset_password"),
    path("reset/<uidb64>/<token>/", ResetPasswordConfirmView.as_view(), name="password_reset_confirm"),
    path("", IndexView.as_view(), name="home"),
    path("help/", DeveloperContactView.as_view(), name="developer"),
    path("feedback/", FeedbackView.as_view(), name="feedback"),
    path("account/", AccountView.as_view(), name="account"),
    path("wrap/<int:pk>", WrappedView.as_view(), name="wrap"),
    path("wrap/<int:pk>/delete", DeleteWrappedView.as_view(), name="delete"),
    path('', include('django.contrib.auth.urls')),
    path("saved/", SavedView.as_view(), name="saved"),

]

wrapped/models.py
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from api.models import SpotifyToken, SpotifyArtist, SpotifyTrack, SpotifyAlbum
from django.core.validators import MaxValueValidator
from django.db import models
import random


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    token = models.OneToOneField(SpotifyToken, null=True, blank=True, on_delete=models.CASCADE)


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


class Feedback(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField(max_length=50)
    subject = models.CharField(max_length=100)
    message = models.CharField(max_length=10000)


post_save.connect(create_user_profile, sender=User)


class SpotifyUserWrap(models.Model):
    THEME = (
        ("no", "None"),
        ("ch", "Christmas"),
        ("hw", "Halloween"),
        ("ea", "Easter"),
    )
    TERMS = (
        ('short', '4 Weeks'),
        ('medium', '6 Months'),
        ('long', '1 Year'),
    )

    created_at = models.DateTimeField(auto_now_add=True)
    theme = models.CharField(default="no", max_length=2, choices=THEME)
    # When the user who generated these wraps deletes their account, the on_delete will delete their wraps
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='wraps')
    term = models.CharField(max_length=6, choices=TERMS)
    public = models.BooleanField(default=False)

    tracks_by_top_artist = models.PositiveIntegerField(default=0)
    top_track_by_top_artist = models.ForeignKey(SpotifyTrack, on_delete=models.CASCADE,
                                                related_name='top_track_by_top_artist_wraps', blank=True, null=True)

    tracks_in_top_album = models.PositiveIntegerField(default=0)
    top_track_in_top_album = models.ForeignKey(SpotifyTrack, on_delete=models.CASCADE,
                                               related_name='top_track_in_top_album_wraps', blank=True, null=True)

    top_track_by_top_artist_of_top_genre = models.ForeignKey(SpotifyTrack, on_delete=models.CASCADE,
                                                             related_name='top_track_by_top_artist_of_top_genre_wraps',
                                                             blank=True, null=True)

    most_popular_track = models.ForeignKey(SpotifyTrack, on_delete=models.CASCADE,
                                           related_name='most_popular_track_wraps',
                                           blank=True, null=True)
    track_popularity = models.CharField(max_length=10, default='0000000000')
    average_popularity = models.FloatField(default=0)
    game_complete = models.BooleanField(default=False)
    score = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(5)])


class TopTrackItem(models.Model):
    wrapped = models.ForeignKey(SpotifyUserWrap, on_delete=models.CASCADE, related_name='top_tracks')
    track = models.ForeignKey(SpotifyTrack, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']


class TopArtistItem(models.Model):
    wrapped = models.ForeignKey(SpotifyUserWrap, on_delete=models.CASCADE, related_name='top_artists')
    artist = models.ForeignKey(SpotifyArtist, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']


class TopAlbumItem(models.Model):
    wrapped = models.ForeignKey(SpotifyUserWrap, on_delete=models.CASCADE, related_name='top_albums')
    album = models.ForeignKey(SpotifyAlbum, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']


class TopGenreItem(models.Model):
    wrapped = models.ForeignKey(SpotifyUserWrap, on_delete=models.CASCADE, related_name='top_genres')
    name = models.CharField(max_length=100)
    freq = models.FloatField()
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']


class TopArtistOfGenre(models.Model):
    genre = models.ForeignKey(TopGenreItem, on_delete=models.CASCADE, related_name='top_artists')
    artist = models.ForeignKey(SpotifyArtist, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']


class TopTrackOfAlbum(models.Model):
    album = models.ForeignKey(TopAlbumItem, on_delete=models.CASCADE, related_name='top_tracks')
    track = models.ForeignKey(SpotifyTrack, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']


class HighLowGameQuestion(models.Model):
    wrapped = models.ForeignKey(SpotifyUserWrap, on_delete=models.CASCADE, related_name='highlow_game_questions')
    track = models.ForeignKey(SpotifyTrack, on_delete=models.CASCADE)
    rank = models.PositiveIntegerField()
    order = models.PositiveIntegerField()
    answer = models.IntegerField()

    class Meta:
        ordering = ['order']


class GuessingGameQuestion(models.Model):
    wrapped = models.ForeignKey(SpotifyUserWrap, on_delete=models.CASCADE, related_name='guess_game_questions')
    track = models.ForeignKey(SpotifyTrack, on_delete=models.CASCADE)
    rank = models.PositiveIntegerField()
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']


class WrappedSlide(models.Model):
    THEMES = (
        ('wrapped1', 'Default 1'),
        ('wrapped2', 'Default 2'),
        ('wrapped3', 'Default 3'),
        ('wrapped4', 'Default 4'),
        ('wrapped5', 'Default 5'),
        ('wrapped6', 'Default 6'),
        ('wrapped7', 'Default 7'),
    )
    LAYOUTS = (
        ('v1', 'Default 1'),
    )

    wrapped = models.ForeignKey(SpotifyUserWrap, on_delete=models.CASCADE, related_name='slides')
    number = models.PositiveIntegerField()
    colors = models.CharField(max_length=10, choices=THEMES, default=None, blank=True, null=True)
    layout = models.CharField(max_length=2, choices=LAYOUTS)

    def save(self, *args, **kwargs):
        if not self.colors:
            self.colors = random.choices(self.THEMES)[0][0]
        if not self.layout:
            self.layout = random.choices(self.LAYOUTS)[0][0]
        super(WrappedSlide, self).save(*args, **kwargs)

    class Meta:
        ordering = ['number']

wrapped/forms.py
from django import forms
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from wrapped.models import Feedback

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.forms import UserChangeForm

class FeedbackForm(forms.ModelForm):
    first_name = forms.CharField(label="First Name", max_length=20)
    last_name = forms.CharField(label="Last Name", max_length=20)
    email = forms.EmailField(label="Email")
    subject = forms.CharField(label="Subject", max_length=100)
    message = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Feedback
        fields = ('first_name', 'last_name', 'email', 'subject', 'message')


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='Enter a valid email address.')

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class AccountForm(forms.Form):
    username = forms.CharField(max_length=250, required=False)
    email = forms.EmailField(required=False)
    current_password = forms.CharField(widget=forms.PasswordInput, required=False)
    new_password = forms.CharField(widget=forms.PasswordInput, required=False)
    confirm_password = forms.CharField(widget=forms.PasswordInput, required=False)
    
    def clean(self):
        cleaned_data = super().clean()

        current_password = cleaned_data.get('current_password')
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')

        if new_password or confirm_password:
            if not current_password:
                raise ValidationError("Current password is required to change the password.")
            if new_password != confirm_password:
                raise ValidationError("New password and confirm password must match.")

        return cleaned_data

templates/wrapped/auth.html
{% extends 'wrapped/layout.html' %}
{% load static %}

{% block title %}{% block name %}{% endblock %}{% endblock %}
{% block css %}{% endblock %}
    
{% block content %}
    <form class="card bg-base-200 shadow-xl col-span-4 md:col-span-6 col-start-1 md:col-start-2 lg:col-start-4" method="POST">
        <div class="card-body">
            {% block heading %}{% endblock %}
            {% block form %}{% endblock %}
            <div class="card-actions justify-center">
                {% block button %}{% endblock %}
            </div>
        </div>
    </form>
{% endblock %}
        
{% block scripts %}{% endblock %}

templates/wrapped/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-theme="spotifyDark">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Spotify Wrapper</title>
        <link rel="stylesheet" href="https://use.typekit.net/qym2xky.css">
        <link rel="stylesheet" href="{% static 'wrapped/css/index.css' %}">
        {% block css %}{% endblock %}
    </head>
    <body class="h-screen flex flex-col items-stretch overflow-hidden">
        <script src="https://colorjs.io/dist/color.global.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js"></script>

        <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/ScrollTrigger.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/ScrollToPlugin.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/TextPlugin.min.js"></script>

        <!-- The following plugins are only available for Club GSAP members.-->
        <script src="{% static 'wrapped/js/gsap/DrawSVGPlugin.min.js' %}"></script>
        <script src="{% static 'wrapped/js/gsap/MorphSVGPlugin.min.js' %}"></script>
        <script src="{% static 'wrapped/js/gsap/ScrollSmoother.min.js' %}"></script>
        <script src="{% static 'wrapped/js/gsap/ScrambleTextPlugin.min.js' %}"></script>
        <script src="{% static 'wrapped/js/gsap/SplitText.min.js' %}"></script>

        <script src="{% static 'wrapped/js/gsap.js' %}"></script>

        <nav>
            <div class="navbar bg-base-200 font-title relative justify-between px-4">
                <div class="absolute inset-0 flex justify-center z-0">
                    <a href="{% url 'wrapped:home' %}" class="text-accent pt-1"><h1>Spotify Wrapper</h1></a>
                </div>
                <div class="flex flex-none lg:hidden z-10 min-h-0 size-10 btn btn-ghost p-0" id="menuControl">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 9h16.5m-16.5 6.75h16.5" />
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 9h16.5m-16.5 6.75h16.5" class="hidden" />
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" class="hidden" />
                    </svg>
                </div>
                <div class="hidden lg:flex z-10">
                    <ul class="menu menu-horizontal px-1 gap-2 items-center">
                        <li class="home"><a class="pt-3" href="{% url 'wrapped:home' %}">
                            {% if user.is_authenticated %}
                                Stats
                            {% else %}
                                Home
                            {% endif %}
                        </a></li>
                        {% if user.is_authenticated %}
                            <li class="saved"><a class="pt-3" href="{% url 'wrapped:saved' %}">Saved</a></li>
                        {% endif %}
                        <li class="help"><a class="pt-3" href="{% url 'wrapped:developer' %}">Contact</a></li>
                    </ul>
                </div>
                <div class="hidden md:flex flex-row z-10 gap-2">
                    {% if user.is_authenticated %}
                        <details class="dropdown dropdown-end">
                            <summary class="after:hidden flex flex-row gap-2 items-center btn btn-neutral btn-ghost !text-base-content">
                                <div class="avatar placeholder" id="avatar">
                                    <div class="bg-neutral text-neutral-content w-10 rounded-full">
                                        <span class="text-xl">{{ user|make_list|first }}</span>
                                        <img alt="Profile Picture" class="hidden" src="" />
                                    </div>
                                </div>
                                <span class="pt-1">{{ user.username }}</span>
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4 chevron transition-transform">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
                                </svg>
                            </summary>
                            <ul class="menu dropdown-content rounded-lg bg-base-200 !mt-5 p-2 w-max right-0 z-50 gap-1">
                                <li><a href="{% url 'wrapped:account' %}" class="pt-3">Account</a></li>
                                <li>
                                    <form method="post" action="{% url 'wrapped:logout' %}" class="p-0 flex flex-col items-stretch hover:bg-error hover:bg-opacity-20 active:!bg-error active:!bg-opacity-40">
                                        {% csrf_token %}
                                        <input class="h-full pb-2 pt-3 px-4 text-error text-left active:!text-error" type="submit" value="Log Out" />
                                    </form>
                                </li>
                            </ul>
                        </details>
                    {% else %}
                        <a href="{% url 'wrapped:login' %}" class="btn btn-ghost btn-accent h-11 min-h-0 pt-1">Log In</a>
                        <a href="{% url 'wrapped:signup' %}" class="btn btn-outline btn-accent h-11 min-h-0 pt-1">Sign Up</a>
                    {% endif %}
                </div>
            </div>
            <div id="menu" class="lg:hidden bg-base-200 absolute inset-x-0 top-16 h-0 overflow-hidden z-50">
                <ul class="menu menu-vertical px-2 gap-2 items-stretch">
                    <li class="home"><a href="{% url 'wrapped:home' %}">
                        {% if user.is_authenticated %}
                            Stats
                        {% else %}
                            Home
                        {% endif %}
                    </a></li>
                    {% if user.is_authenticated %}
                        <li class="saved"><a href="{% url 'wrapped:saved' %}">Saved</a></li>
                    {% endif %}
                    <li class="help"><a href="{% url 'wrapped:developer' %}">Contact</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'wrapped:account' %}">Account</a></li>
                        <li><a href="{% url 'wrapped:logout' %}" class="text-error hover:bg-error hover:bg-opacity-20 active:!text-error active:!bg-error active:!bg-opacity-40">Log Out</a></li>
                    {% else %}
                        <li class="flex md:hidden"><a class="text-primary active:!text-primary" href="{% url 'wrapped:login' %}">Log In</a></li>
                        <li class="flex md:hidden"><a class="text-secondary active:!text-secondary" href="{% url 'wrapped:signup' %}">Sign Up</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <main class="grow shrink max-h-screen relative bg-base-100 font-body p-3 overflow-y-scroll">
            {% if messages %}
                <div id="messages" class="absolute inset-x-0 top-0 flex flex-col items-center pt-2">
                    {% for message in messages %}
                        <div class="pb-2 z-40 message">
                            <div class="card shadow-xl text-center flex flex-row items-center gap-2 p-2 h-10 text-{{ message.tags }} {% if message.tags == 'success' %}bg-green-200{% elif message.tags == 'error' %}bg-red-200{% else %}bg-base-300{% endif %}">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m9-.75a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 3.75h.008v.008H12v-.008Z" />
                                </svg>
                                <span>{{ message }}</span>
                                <button class="btn btn-{{ message.tags }} btn-ghost min-h-0 h-6 min-w-0 px-1 close" type="button" data-dismiss="alert" aria-hidden="true">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
                                    </svg>
                                </button>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="grid-content w-full overflow-visible min-h-[calc(100vh-6rem)]">
                {% block content %}
                {% endblock %}
            </div>
            <button class="btn btn-primary fixed right-4 bottom-4 size-12 flex justify-center items-center rounded-full z-20" id="theme">
                <label class="swap swap-rotate size-8">
                    <input type="checkbox" id="themeControl" checked />
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8 swap-off">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 3v2.25m6.364.386-1.591 1.591M21 12h-2.25m-.386 6.364-1.591-1.591M12 18.75V21m-4.773-4.227-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z" />
                    </svg>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8 swap-on">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M21.752 15.002A9.72 9.72 0 0 1 18 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 0 0 3 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 0 0 9.002-5.998Z" />
                    </svg>
                </label>
            </button>
        </main>

        <script>placeholder = '{% static 'wrapped/img/placeholder.png' %}';</script>

        <script src="{% static 'wrapped/js/globals.js' %}"></script>
        <script src="{% static 'wrapped/js/request.js' %}"></script>
        <script src="{% static 'wrapped/js/menu.js' %}"></script>
        <script src="{% static 'wrapped/js/theme.js' %}"></script>
        <script src="{% static 'wrapped/js/messages.js' %}"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

templates/wrapped/linking.html
{% extends 'wrapped/layout.html' %}
{% load static %}

{% block title %}Connecting{% endblock %}
{% block css %}{% endblock %}
    
{% block content %}
    <div class="col-span-4 col-start-1 md:col-start-3 lg:col-start-5 text-center flex flex-col items-center gap-3">
        {% if not user.is_authenticated %}
            <h3>Unable to Link Your Spotify Account</h3>
            <p>Your Spotify account could not be linked because you are not logged into Spotify Wrapper.</p>
            <a id="goHome" href="{% url 'wrapped:home' %}" class="btn btn-accent">Go Back Home</a>
        {% else %}
            <h3>Linking Your Spotify Account</h3>
            <p>You should be redirected automatically on success.</p>
            <a id="goHome" href="{% url 'wrapped:home' %}" class="btn btn-accent">Go Back Home</a>
        {% endif %}
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'wrapped/js/request.js' %}"></script>
    <script>document.addEventListener('DOMContentLoaded', getLinkToken)</script>
{% endblock %}

templates/wrapped/login.html
{% extends 'wrapped/auth.html' %}

{% block name %}Log In{% endblock %}
{% block heading %}<h1 class="text-center">Log In</h1>{% endblock %}
{% block form %}
    {% csrf_token %}
    {{ form }}
    <a class="!link !link-accent text-center" href="{% url 'wrapped:reset_password' %}">Forgot Password</a>
{% endblock %}
{% block button %}<button type="submit" class="btn btn-accent">Log In</button>{% endblock %}

templates/wrapped/password_reset.html
{% extends "wrapped/layout.html" %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'wrapped:signup' %}">Create A New Account</a><br><br>
                                <a href="{% url 'wrapped:login' %}">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>
{% endblock content %}

templates/wrapped/signup.html
{% extends 'wrapped/auth.html' %}

{% block name %}Sign Up{% endblock %}
{% block heading %}<h1 class="text-center">Sign Up</h1>{% endblock %}
{% block form %}
    {% csrf_token %}
    {{ form }}
    <a class="!link !link-accent text-center" href="{% url 'wrapped:home' %}">Already have an account</a>
{% endblock %}
{% block button %}<button type="submit" class="btn btn-accent">Sign Up</button>{% endblock %}